[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "python -m pip install -e ."
]

[start]
cmd = "python scripts/run_mainnet_stream.py"
